oc_platform_homepage:
    path:     /
    defaults: { _controller: OCPlatformBundle:Default:index }

oc_platform_hello:
    path:   /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index }