#oc_platform_hello:
#    path:   /hello-world
#    defaults: { _controller: OCPlatformBundle:Advert:index }
# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /{page}
    defaults:  
        _controller: OCPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*
    
oc_platform_view:
    path:      /advert/{id}
    defaults: 
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+
        
oc_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatformBundle:Advert:Add }

oc_platform_edit:
    path: /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:Edit
    requirements:
        id: \d+
        
oc_platform_delete:
    path: /del/{id}
    defaults: 
        _controller: OCPlatformBundle:Advert:Delete
    requirements:
        id: \d+

oc_platform_view_slug:
    path:      /platform/{year}/{slug}.{_format}
    defaults: 
        _controller: OCPlatformBundle:Advert:viewSlug
        _format: json
    requirements:
        year:   \d{4}
        format: html|json