services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: [ "@mailer", 50]
        calls:
           - [setLocale, [%locale%]]

    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@oc_platform.antispam"
        tags:
            - { name: twig.extension }

    oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: ["@mailer"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.form.ckeditor:
        class: OC\PlatformBundle\Form\CKEditorType
        tags:
            - { name: form.type, alias: ckeditor}

    oc_platform.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
            - "@oc_platform.beta.html_adder"
            - "2017-06-01"
        tags:
            - {name: kernel.event_listener, event: kernel.response, method: processBeta}