services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: [ "@mailer", %locale%, 50]

    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@oc_platform.antispam"
        tags:
            - { name: twig.extension }

    oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: ["@mailer"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }