<?php

namespace OC\PlatformBundle\Repository;
use Doctrine\DBAL\Query\QueryBuilder;
use Symfony\Component\Validator\Constraints\DateTime;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    //Recupèere toutes les annonces
    public function getAdverts($page, $nbPerPage){
        $query = $this->createQueryBuilder('a')
            //jointure table images
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            //Jointure catégories
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->orderBy('a.date','DESC')
            ->getQuery();
        //return $query->getResult();

        $query->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);
        return new Paginator($query, true);
    }
    public function myFindAll(){
        return $this->createQueryBuilder('a')
            ->getQuery()
            ->getResult();
    }

    public function myFindOne($id){
        return $this->createQueryBuilder('a')
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

    public function findByAuthorAndDate($author, $date){
        return $this->createQueryBuilder('a')
            ->where('a.author = :author')->setParameter('author', $author)
            ->andWhere('a.date < :date')->setParameter('date', $date)
            ->getQuery()
            ->getResult();
    }

    public function whereCurrentYear(QueryBuilder $qb){
        $qb->andWhere('a.date BETWEEN :start AND :end')
            ->setParameter('start', new \DateTime(date('Y').'-01-01'))
            ->setParameter('end', new DateTime(date('Y').'-12-31'));

    }

    public function getAdvertsWithApplications(){
        return $this->createQueryBuilder('a')
            ->leftJoin('a.applications', 'app')
            ->addSelect('app')
            ->getQuery()
            ->getResult();
    }

    public function getAdvertsWithCategories(array $categoryNames){
         $qb = $this->createQueryBuilder('a');
         $qb->leftJoin('a.categories', 'cat')
            ->addSelect('cat');
         $qb->where($qb->expr()->in('cat.name', $categoryNames));

         return $qb->getQuery()
                    ->getResult();
    }
}
